### ISSUE TITLE
Incompatibility with Flarum Blog Extension

### ISSUE THREAD

**Issue by iamdarkle** [android-com-pl/my-tags#1]
There is a bug that cuts off the blog categories when activating this extension.

With the extension activated:
![msedge_38wammiiXx](https://user-images.githubusercontent.com/15818451/126044570-d8b5d87a-80b6-4af9-8efc-645054827b69.png)
Without the extension activated:
![msedge_TsfSCrvVUE](https://user-images.githubusercontent.com/15818451/126044573-15583210-e55b-42af-aea3-bbcdbe07d2b3.png)

**Comment by rafaucau** [comment]
@iamdarkle I can't reproduce it. Flarum Blog Extension does not load all the tags even when I turn off My Tags.
It only loads all of them when I go to the tags page first and then to the blogs page.

It looks to me like a problem with the Blogs extension itself

**Comment by rafaucau** [comment]
It looks to me like a problem with the Blogs extension itself

**Comment by rafaucau** [comment]
I am closing this issue for now. If you have more information, you can open it

**Comment by iamdarkle** [comment]
@rafaucau Thanks 1.1.1 did fix it, sorry I forgot this, I had planned to do some testing to find out what caused this bug, but I kept putting it off until I completely forgot. Thank you very much!
